#Name of the GitHub Action
name: "Newman Tests"

#Set the action on which the workflow will trigger
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run GOREST-API-TESTING.postman_collection.json -e Test-Environment.postman_environment.json
